# site settings
title: Seize Change
subtitle: 2019
email: info@seize-change.org
description: Reframing the face of adventue
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Nic Annau
#street_address: 1234 Somewhere Road
city: Victoria
state: British Columbia
#zip_code: 55555
country: Canada
phone: 1 778 980 7423

# social settings
500px_url:
facebook_url:
github_url: https://github.com/seize-change
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url:
instagram_url: https://www.instagram.com/seizechange/
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
twitter_url: https://twitter.com/seizechange
facebook_url: https://www.facebook.com/seizechange/

# build settings
markdown: kramdown

sass:
  style: compressed
