# Site settings
title: Seize Change
email: sailingforscience@gmail.com
url: https://nannau.github.io/seize_change
description: "A 3 month sailing journey through the Inside Passage to raise awareness, and collect data, of marine debris along the coastlines of BC and Alaska.  We hope to reframe the face of adventure and inspire others to be stewards of the earth as they venture into the outdoors."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Seize Change

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
 # - title: twitter
 #   url: https://twitter.com/SBootstrap
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
 # - title: github
 #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
