# Site settings
title: Seize Change
email: info@seize-change.org
url: https://seize_change/seize-change.github.io

description: "Reframing the face of adventure"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  primary-dark-nav: '#ffffff'
  links: '#164ca3'

# Footer settings
footer: Seize Change

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/seizechange
  - title: facebook
    url: https://facebook.com/seizechange
  - title: instagram
    url: https://www.instagram.com/seizechange
  - title: github
    url: https://github.com/seize-change
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
repository: seize-change/seize-change.github.io

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

# Build settings
markdown: kramdown
permalink: pretty
