# Site settings
title: Seize Change
email: sailingforscience@gmail.com
url: https://nannau.github.io/seize_change
description: "Reframing the face of adventure"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#1a4182'
  primary-dark-nav: '#0e2244'
  links: '#219ab3'

# Footer settings
footer: Seize Change

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://facebook.com
  - title: instagram
    url: https://www.instagram.com/nannauman/
  - title: github
    url: https://github.com/seize-change
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll


# Build settings
markdown: kramdown
permalink: pretty
